version: 2

project_name: fastGit

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: ./cmd/fastgit
    binary: fastGit
    ldflags:
      - -s -w -X github.com/KevinYouu/fastGit/internal/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^assets:'

snapshot:
  version_template: '{{ incpatch .Version }}'
